Motd: '&6&lBLATANT&f&lMC &aPlugin iniciado!'
StatusMotd: '&6Modo: &7KitPvP'
NomeServer: '&6&lBLATANT&f&lMC'
MensagemAutomatica1: '&fAcesse o discord do servidor &3(&7https://discord.gg/eWvbNxw&3)'
MensagemAutomatica2: '&fCaso queria se aplicar para a &d&lSTAFF&f do servidor use &7/aplicar'
MensagemAutomatica3: '&fQuer virar um &b&lYOUTUBER &fdo servidor? use &7/youtuber'
MensagemAutomatica4: '&fAchou um &4&lHACKER &fno servidor? use &7/report'
MensagemAutomatica5: '&fFique sabendo das &2&lREGRAS&f do servidor usando &7/regras'
MensagemAplicar1: '&fFormularios em nosso discord: &3(&7https://discord.gg/eWvbNxw&3)'
MensagemYoutuber1: '&bPara se tornar YT No Servidor Necessita-se de 250 Subs + Video No Servidor'
MensagemYoutuber2: '&cEssa TAG Não é Liberada'
MensagemYoutuber3: '&cEssa TAG Não é Liberada'