name: PvP
main: pvp.blatantmc.main.Main
author: Tijela_Quebrada
description: Plugin para StarMC
version: 1.0
commands:
  fly:
  internet:
  cage:
  twitter:
  skit:
  discord:
  uncage:
  ping:
  tpall:
  clan:
  tp:
  regras:
  sc:
  report:
  status:
  ranks:
  xp:
  kit:
  gm:
  gamemode:
  build:
  admin:
  pvp:
  tag:
  warp:
  setwarp:
  aviso:
  cc:
  tell:
  chat:
  aplicar:
  caixa:
  setarena:
  spawn:
  youtuber: